### ISSUE TITLE
Looking for non existing ~/.config/toolbag.config.json

### ISSUE THREAD

**Issue by Minipada** [ericanderson/ghouls#1]
Hello,
Thanks for the project, can be very handy. I was trying to run it but I couldn't start it.
I did `yarn add config.json` and added `~/.yarn/bin` in my path and tried to run it but I'm encountering an issue related to a missing file.
Would you know where to find `~/.config/toolbag.config.json`

```
ghouls [master●●] % ghouls prunePullRequests minipada/<whatever>
ghouls prunePullRequests [--dry-run] <repo>

Prunes remote branches that have already been merged

Positionals:
  repo                                                       [string] [required]

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

{ Error: ENOENT: no such file or directory, open '/home/<user>/.config/toolbag.config.json'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at loadFile (/home/david/.config/yarn/global/node_modules/convict/lib/convict.js:447:19)
    at /home/david/.config/yarn/global/node_modules/convict/lib/convict.js:589:17
    at Array.forEach (<anonymous>)
    at Object.loadFile (/home/david/.config/yarn/global/node_modules/convict/lib/convict.js:588:13)
    at Object.getConfig (/home/david/.config/yarn/global/node_modules/ghouls/src/utils/getConfig.ts:29:10)
    at Object.handler (/home/david/.config/yarn/global/node_modules/ghouls/src/commands/PrunePullRequests.ts:19:25)
    at Object.runCommand (/home/david/.config/yarn/global/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/david/.config/yarn/global/node_modules/yargs/yargs.js:1014:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/<user>/.config/toolbag.config.json' }
```

**Comment by Minipada** [comment]
I figured out the file named in the readme was the one missing and wanted, after trying to run, I got this. Would you have any idea?

```
TypeError: Symbol.asyncIterator is not defined.
    at __asyncGenerator (/home/david/.config/yarn/global/node_modules/ghouls/lib/OctokitPlus.js:4:38)
    at createAsyncIterator (/home/david/.config/yarn/global/node_modules/ghouls/lib/OctokitPlus.js:60:12)
    at OctokitPlus.getPullRequests (/home/david/.config/yarn/global/node_modules/ghouls/src/OctokitPlus.ts:86:12)
    at PrunePullRequest.perform (/home/david/.config/yarn/global/node_modules/ghouls/src/commands/PrunePullRequests.ts:53:43)
    at Object.handler (/home/david/.config/yarn/global/node_modules/ghouls/src/commands/PrunePullRequests.ts:25:28)
    at Object.runCommand (/home/david/.config/yarn/global/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/david/.config/yarn/global/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/home/david/.config/yarn/global/node_modules/yargs/yargs.js:957:21)
    at Object.cli [as default] (/home/david/.config/yarn/global/node_modules/ghouls/src/cli.ts:12:12)
    at Object.<anonymous> (/home/david/.config/yarn/global/node_modules/ghouls/bin/ghouls:3:65)
```

**Comment by ericanderson** [comment]
@Minipada Sorry I never saw this. Probably an old node version. If its still failing, mind reporting what version of node you are using?
